openapi: 3.0.3
info:
  title: CityQuest API
  description: Dokumentation aller Schnittstellen
  version: 1.0.0
servers:
  - url: https
paths:
  /register:
    post:
      tags:
        - public
      description: Benutzer registriert sich
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Registrierungsdaten
              example:
                username: DanielPillwein
                password: ichbinreich10!
                email: daniel.pillwein@htl.rennweg.at
      responses:
        '201':
          content:
            application/json:
              example:
                user:
                  id: 10
                  name: DanielPillwein
                  email: daniel.pillwein@htl.rennweg.at
                emailVerified: false
          description: JSON des hinzugefügten Benutzers
        '400':
          content:
            application/json:
              example:
                error: Der Benutzername oder die Email existiert bereits
          description: Der Benutzername oder die Email existiert bereits
  /login:
    post:
      tags:
        - public
      description: Benutzer loggt sich ein.
      security:
        - { }
      requestBody:
        required: true
        description: Zugangsdaten
        content:
          application/json:
            schema:
              example:
                username: WizMarki
                password: stubsi10!
      responses:
        '200':
          content:
            application/json:
              example:
                sessionKey: Lu9Tc1Pdola+SOnfPUxEkoKYuQLdjmsMK89uxT+RrrVegf1xQOI6Mpv5IXrYX6CVsukFLhwGzNH/zLMsuoBSbQ==
              schema:
                type: string
                properties:
                  sessionKey:
                    type: string
          description: Erfolgreich eingeloggt. Gibt *sessionKey* zurück
        '400':
          content:
            application/json:
              example:
                error: Falscher Benutzername oder falsches Passwort
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Die Fehlermeldung
          description: Falscher Benutzername oder falsches Passwort
        '401':
          content:
            application/json:
              example:
                error: Die E-Mail-Adresse wurde noch nicht verifiziert
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Die Fehlermeldung
          description: Die E-Mail-Adresse wurde noch nicht verifiziert
  /verify:
    post:
      tags:
        - public
      description: Verifiziert die E-Mail-Adresse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                key: aa234adsklvneoiadv
                email: 9137@htl.rennweg.at
      responses:
        201:
          description: E-Mail-Adresse verifiziert
        401:
          description: Verifizierungs-Key existiert nicht oder ist abgelaufen
          content:
            application/json:
              example:
                error: Der Verifizierungs-Link ist ungültig oder abgelaufen
  /forgotpassword:
    get:
      tags:
        - public
      description: Es wird eine Email verschickt mit der das Passwort zurückgesetzt werden kann
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                email: 9137@htl.rennweg.at
      responses:
        201:
          description: Email wurde verschickt
        400: 
          description: Es existiert keine Benutzer mit der Email-Adresse
          content:
            application/json:
              example:
                error: Es gibt keinen Benutzer mit der angegebenen Email-Adresse
  /changepassword:
    patch:
      tags:
        - public
      description: Mit Zugriff auf die E-Mail-Adresse kann ich mein Passwort ändern
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                key: aa234adsklvneoiadv
                email: 9137@htl.rennweg.at
                new_password: Teesstt123!
      responses:
        204:
          description: Password wurde geändert
        401:
          description: Verifizierungs-Key existiert nicht oder ist abgelaufen
          content:
            application/json:
              example:
                error: Der Passwort-Vergessen-Link ist ungültig oder abgelaufen
  /getusers:
    get:
      tags:
        - auth
      description: Prüft ob der gesetzte API-Token des Benutzers gültig ist
      security:
        - ApiKeyAuth: [ ]
      responses:
        '200':
          description: Benutzer erkannt
          content:
            application/json:
              example:
                id: 10
                name: Quantom
                email: Quantom@myemail.com
  /deleteusers:
    delete:
      tags:
        - auth
      description: Löscht den eigenen Benutzer
      security:
        - ApiKeyAuth: [ ]
      responses:
        200:
          description: Dein Benutzer wurde gelöscht
        400:
          content:
            application/json:
              example:
                error: Es gibt keinen Benutzer mit diesem Token
          description: Der Benutzer existiert nicht
  /changepasswordauth:
    patch:
      tags:
        - auth
      description: Ein angemeldeter Benutzer kann sein Passwort ändern
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                old_password: altesPasswort
                new_password: Teesstt123!
      responses:
        201:
          description: Password wurde geändert
        401:
          description: Altes Passwort ist falsch
          content:
            application/json:
              example:
                error: Das angegebene Passwort ist falsch
  /logout:
    post:
      tags:
        - auth
      description: Benutzer loggt sich aus
      security:
        - ApiKeyAuth: [ ]
      responses:
        '204':
          description: User wurde abgemeldet
        '400':
          content:
            application/json:
              example:
                error: Es gibt keinen Benutzer mit diesem Token
          description: Es gibt keinen Benutzer mit diesem Token
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      bearerFormat: TOKEN
